version: '3'
services:
    app:
        image: app:latest
        user: root
        volumes:
            - ../barbershop:/home:rw

    postgres:
        image: postgres:15
        user: root
        ports:
            - 5432:5432
        volumes:
            - ./compose/data:/var/lib/postgresql/data:rw
            - ./compose/var/run:/var/run:rw
            - ./compose/initdb.d:/docker-entrypoint-initdb.d:ro
        environment:
          POSTGRES_USER: sheeesh
          POSTGRES_PASSWORD: sheeesh

    pgadmin:
        image: dpage/pgadmin4
        user: root
        depends_on:
            - postgres
        ports:
            - 5050:5050
        environment:
            PGADMIN_DEFAULT_EMAIL: user@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 1234
            PGADMIN_LISTEN_PORT: 5050
        volumes:
            - ./compose/var/lib/pgadmin:/var/lib/pgadmin:rw